#ifndef _libiqnet_ssl_lib_h_
#define _libiqnet_ssl_lib_h_

#include <openssl/ssl.h>
#include <stdexcept>

namespace SSL_lib 
{
  //! Global SSL context.
  extern SSL_CTX* ctx;
    
  /*!
  \fd SSL_lib::init
  \brief OpenSSL library init.
  \param cert_path Path to certificate file.
  \param key_path Path to private key file.
  */
  void init( const std::string& cert_path, const std::string& key_path );

  class error;
};


//! Exception class to wrap errors generated by openssl library.
class SSL_lib::error: public std::runtime_error {
public:
  error();
  error( int ssl_err );
  error( SSL*, int ret );
};

  
#endif
